### PR TITLE
Updated babel-eslint and babel

### PR DESCRIPTION
**Pull request by justin808**
* Turned off jsdoc, as new version of eslint fails
* Turned on paded-blocks

Changes to shrinkwrap are due to update to 0.12.2 of node.

### CODE REVIEW

**Comment by justin808** [comment]
@mbreining can you please try this out?

**Comment by justin808** [comment]
@mbreining @geoffevason What do you two think? FWIW, airbnb doesn't use it. I'm just throwing it out there so you can see what js-doc is about.

```

assets/javascripts/actions/CommentActions.js
   5:2  error  Missing JSDoc parameter description for 'url'             valid-jsdoc
   5:2  error  Missing JSDoc parameter description for 'displaySpinner'  valid-jsdoc
   5:2  error  Missing JSDoc return description                          valid-jsdoc
  19:2  error  Missing JSDoc parameter description for 'comments'        valid-jsdoc
  19:2  error  Missing JSDoc return description                          valid-jsdoc
  29:2  error  Missing JSDoc parameter description for 'errorMessage'    valid-jsdoc
  29:2  error  Missing JSDoc return description                          valid-jsdoc
  39:2  error  Missing JSDoc parameter description for 'comment'         valid-jsdoc
  39:2  error  Missing JSDoc return description                          valid-jsdoc

assets/javascripts/actions/FormActions.js
   6:2  error  Missing JSDoc parameter description for 'comment'  valid-jsdoc
   6:2  error  Missing JSDoc return description                   valid-jsdoc
  16:2  error  Missing JSDoc parameter description for 'comment'  valid-jsdoc
  16:2  error  Missing JSDoc return description                   valid-jsdoc
  16:2  error  Expected JSDoc for 'url' but found 'comment'       valid-jsdoc

assets/javascripts/utils/CommentsManager.js
   4:2  error  Missing JSDoc parameter description for 'url'      valid-jsdoc
   4:2  error  Missing JSDoc return description                   valid-jsdoc
  17:2  error  Missing JSDoc parameter description for 'url'      valid-jsdoc
  17:2  error  Missing JSDoc parameter description for 'comment'  valid-jsdoc
  17:2  error  Missing JSDoc return description                   valid-jsdoc

✖ 19 problems (19 errors, 0 warnings)
```

**Comment by justin808** [comment]
@mbreining @geoffevason Can you give this the :+1: ?

I fixed the jsdoc issues. Pretty nice! I dig it!

**Comment by mbreining** [comment]
Looks good to me.

**Pull request merged**
