### PR TITLE
Update libraries and JSX for current versions 1/23/2015

### PR DESCRIPTION
**Pull request by justin808**
* Required a few JSX changes.
* Don't use import for commonjs modules
* key changed to eventKey for NavItem
* Use different names for the the native input HTML elements compared to
  the react-bootstrap ones
* Could not update the sass-loader without errors
* Moved all Sass related parts of webpack to the webpack.hot.config.js
  as Rails version does not use the Webpack sass handlers.
* Changed webpack.rails.config.js so that the loader for JSX does not
  use react-hot
* Added the woff2 pattern for the file loader.
* Changed from React.renderComponent to React.render in example.jsx.

### CODE REVIEW

**Comment by justin808** [comment]
@mbreining @kimagure Any comments? I'll try to get the sass-loader updated next.

**Comment by kimagure** [comment]
You can import CommonJS modules easily, just requires that you do `import * as YOURNAME from 'module'`

I admit it's not the best thing ever, but it'll work enough.

**Comment by mbreining** [comment]
@justin808, the code in ```update-to-latest``` is deploying to Heroku fine but is not functional (none of the forms are showing up). The same issue exist on ```master```. I'll have to look into it.

**Comment by mbreining** [comment]
You can merge as far as I'm concerned.

**Comment by justin808** [comment]
@mbreining I rebased master onto my branch and did a push -f.

**Pull request merged**
