### PR TITLE
Address some outstanding issues with Alt -> Flux migration

### PR DESCRIPTION
**Pull request by PlasticLizard**
* Fix bug preventing ajax loader from working
* Reset the comment form only upon success
* Display errors on the comment form and comment list if communication with the server fails

### CODE REVIEW

**Comment by justin808** [comment]
@mapreal19 Please work with @PlasticLizard on getting his changes merged with yours.

**Comment by mapreal19** [comment]
@justin808 just rebased [PR-68](https://github.com/justin808/react-webpack-rails-tutorial/pull/68) on top of this branch. Now seems good to go :ship:

**Comment by justin808** [comment]
@PlasticLizard @mapreal19 Super! @PlasticLizard Please let me know if you have any opinions, before merging to master.

**Comment by PlasticLizard** [comment]
Looks great, love the improvements to the tests.

**Comment by justin808** [comment]
I'll merge this evening then. And the next one then is put in server rendering: https://github.com/shakacode/react_rails_server_rendering

If either of you want to try this, let me know.

/spec/dummy in that gem repo has a sample app...

I'll push the ruby gem this evening...However, like the /spec/dummy app, you can try this all with a local copy of the git repo of the gem.

**Pull request merged**
