### PR TITLE
Several slight enhancements, most importantly sanitization

### PR DESCRIPTION
**Pull request by justin808**
1. Markdown is github flavored and sanitized
2. Some help text explaining that text is treated as markdown
3. Rake task to delete tasks older than 24 hours

### CODE REVIEW

**Comment by justin808** [comment]
Before this change, an iframe could be placed.
cursor

**Comment by alexfedoseev** [comment]
LGTM

**Comment by justin808** [comment]
Job added

cursor_and_heroku_scheduler

**Comment by justin808** [comment]
cursor_and_railsreacttutorial

Then

cursor_and_railsreacttutorial

**Comment by justin808** [comment]
cursor_and_railsreacttutorial

**Comment by justin808** [comment]
https://github.com/chjj/marked

cursor_and_chjj_marked

**Pull request merged**
