### PR TITLE
Fix Lint Errors

### PR DESCRIPTION
**Pull request by mapreal19**

### CODE REVIEW

**Comment by justin808** [comment]
@mapreal19: I get a lot more lint issues:

```
rake ci                                     [20:46:01]
Running Rubocop Linters via `rubocop -S -D .`
rubocop -S -D .
Warning: Deprecated pattern style '/Users/justin/a/react-webpack-rails-tutorial/client/node_modules/**/*' in /Users/justin/a/react-webpack-rails-tutorial/.rubocop.yml
Inspecting 28 files
............................

28 files inspected, no offenses detected
Running ruby-lint Linters via `ruby-lint app config spec lib`
ruby-lint app config spec lib
Running eslint via `cd client && npm run eslint . -- --ext .jsx,.js`
cd client && npm run eslint . -- --ext .jsx,.js

> react-webpack-rails-tutorial@1.1.0 eslint /Users/justin/a/react-webpack-rails-tutorial/client
> eslint "." "--ext" ".jsx,.js"


assets/javascripts/actions/CommentActionCreators.js
  62:9  error  comment is already declared in the upper scope  no-shadow

assets/javascripts/components/CommentBox.jsx
  15:9   error  `fetchComments` is never modified, use `const` instead  prefer-const
  21:3   error  ajaxCounter must be placed after render                 react/sort-comp
  33:22  error  JSX attributes must use doublequote                     react/jsx-quotes

assets/javascripts/components/CommentForm.jsx
   29:3   error  handleSelect must be placed after render                    react/sort-comp
   63:5   error  Expected exception block, space or tab after // in comment  spaced-comment
   65:29  error  Missing space before value for key "author"                 key-spacing
   65:54  error  A space is required after ','                               comma-spacing
   65:60  error  Missing space before value for key "text"                   key-spacing
   65:63  error  Missing semicolon                                           semi
   68:33  error  Missing space before opening brace                          space-before-blocks
   69:45  error  Missing semicolon                                           semi
   71:52  error  Missing semicolon                                           semi
   80:25  error  JSX attributes must use doublequote                         react/jsx-quotes
   81:23  error  JSX attributes must use doublequote                         react/jsx-quotes
   81:36  error  JSX attributes must use doublequote                         react/jsx-quotes
   81:55  error  JSX attributes must use doublequote                         react/jsx-quotes
   81:82  error  JSX attributes must use doublequote                         react/jsx-quotes
   82:35  error  JSX attributes must use doublequote                         react/jsx-quotes
   83:22  error  JSX attributes must use doublequote                         react/jsx-quotes
   85:23  error  JSX attributes must use doublequote                         react/jsx-quotes
   85:40  error  JSX attributes must use doublequote                         react/jsx-quotes
   86:33  error  JSX attributes must use doublequote                         react/jsx-quotes
   87:35  error  JSX attributes must use doublequote                         react/jsx-quotes
   87:51  error  JSX attributes must use doublequote                         react/jsx-quotes
   91:26  error  JSX attributes must use doublequote                         react/jsx-quotes
   92:28  error  JSX attributes must use doublequote                         react/jsx-quotes
   92:68  error  JSX attributes must use doublequote                         react/jsx-quotes
   93:73  error  JSX attributes must use doublequote                         react/jsx-quotes
   94:69  error  JSX attributes must use doublequote                         react/jsx-quotes
  107:25  error  JSX attributes must use doublequote                         react/jsx-quotes
  108:23  error  JSX attributes must use doublequote                         react/jsx-quotes
  108:36  error  JSX attributes must use doublequote                         react/jsx-quotes
  108:55  error  JSX attributes must use doublequote                         react/jsx-quotes
  108:71  error  JSX attributes must use doublequote                         react/jsx-quotes
  111:23  error  JSX attributes must use doublequote                         react/jsx-quotes
  111:40  error  JSX attributes must use doublequote                         react/jsx-quotes
  111:81  error  JSX attributes must use doublequote                         react/jsx-quotes
  114:23  error  JSX attributes must use doublequote                         react/jsx-quotes
  114:42  error  JSX attributes must use doublequote                         react/jsx-quotes
  114:66  error  JSX attributes must use doublequote                         react/jsx-quotes
  125:25  error  JSX attributes must use doublequote                         react/jsx-quotes
  126:24  error  JSX attributes must use doublequote                         react/jsx-quotes
  126:55  error  JSX attributes must use doublequote                         react/jsx-quotes
  129:29  error  JSX attributes must use doublequote                         react/jsx-quotes
  129:46  error  JSX attributes must use doublequote                         react/jsx-quotes
  129:73  error  JSX attributes must use doublequote                         react/jsx-quotes
  130:28  error  JSX attributes must use doublequote                         react/jsx-quotes
  135:29  error  JSX attributes must use doublequote                         react/jsx-quotes
  135:46  error  JSX attributes must use doublequote                         react/jsx-quotes
  136:28  error  JSX attributes must use doublequote                         react/jsx-quotes
  141:29  error  JSX attributes must use doublequote                         react/jsx-quotes
  141:48  error  JSX attributes must use doublequote                         react/jsx-quotes
  141:72  error  JSX attributes must use doublequote                         react/jsx-quotes
  152:5   error  Expected exception block, space or tab after // in comment  spaced-comment
  155:22  error  JSX attributes must use doublequote                         react/jsx-quotes
  155:35  error  JSX attributes must use doublequote                         react/jsx-quotes
  158:6   error  Missing semicolon                                           semi
  165:7   error  Expected indentation of 4 characters but found 6            indent
  166:9   error  Expected indentation of 6 characters but found 8            indent
  167:9   error  Expected indentation of 6 characters but found 8            indent
  168:7   error  Expected indentation of 4 characters but found 6            indent
  169:9   error  Expected indentation of 6 characters but found 8            indent
  170:9   error  Expected indentation of 6 characters but found 8            indent
  171:7   error  Expected indentation of 4 characters but found 6            indent
  172:9   error  Expected indentation of 6 characters but found 8            indent
  173:9   error  Expected indentation of 6 characters but found 8            indent
  174:7   error  Expected indentation of 4 characters but found 6            indent
  175:9   error  Expected indentation of 6 characters but found 8            indent
  175:9   error  Expected an object to be thrown                             no-throw-literal
  184:22  error  JSX attributes must use doublequote                         react/jsx-quotes

assets/javascripts/components/CommentList.jsx
  14:3   error  errorWarning must be placed after render                    react/sort-comp
  15:5   error  Expected exception block, space or tab after // in comment  spaced-comment
  18:22  error  JSX attributes must use doublequote                         react/jsx-quotes
  18:35  error  JSX attributes must use doublequote                         react/jsx-quotes
  21:6   error  Missing semicolon                                           semi
  21:10  error  Trailing spaces not allowed                                 no-trailing-spaces
  36:49  error  JSX attributes must use doublequote                         react/jsx-quotes
  39:24  error  JSX attributes must use doublequote                         react/jsx-quotes

assets/javascripts/components/CommentScreen.jsx
  22:23  error  'data' is missing in props validation  react/prop-types
  31:24  error  JSX attributes must use doublequote    react/jsx-quotes
  32:19  error  JSX attributes must use doublequote    react/jsx-quotes
  33:27  error  JSX attributes must use doublequote    react/jsx-quotes
  34:30  error  JSX attributes must use doublequote    react/jsx-quotes
  38:19  error  JSX attributes must use doublequote    react/jsx-quotes
  39:28  error  JSX attributes must use doublequote    react/jsx-quotes
  45:4   error  Missing trailing comma                 comma-dangle

assets/javascripts/reducers/commentReducer.js
   5:22  error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap
   6:13  error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap
  14:5   error  Expected indentation of 2 characters but found 4                                               indent
  15:7   error  Expected indentation of 4 characters but found 6                                               indent
  16:5   error  Expected indentation of 2 characters but found 4                                               indent
  17:7   error  Expected indentation of 4 characters but found 6                                               indent
  18:5   error  Expected indentation of 2 characters but found 4                                               indent
  19:7   error  Expected indentation of 4 characters but found 6                                               indent
  21:61  error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap
  24:5   error  Expected indentation of 2 characters but found 4                                               indent
  25:7   error  Expected indentation of 4 characters but found 6                                               indent
  26:5   error  Expected indentation of 2 characters but found 4                                               indent
  27:7   error  Expected indentation of 4 characters but found 6                                               indent
  28:5   error  Expected indentation of 2 characters but found 4                                               indent
  29:7   error  Expected indentation of 4 characters but found 6                                               indent
  30:5   error  Expected indentation of 2 characters but found 4                                               indent
  31:7   error  Expected indentation of 4 characters but found 6                                               indent

✖ 104 problems (104 errors, 0 warnings)


npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/justin/.nvm/versions/node/v0.12.7/bin/npm" "run" "eslint" "." "--" "--ext" ".jsx,.js"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-rails-tutorial@1.1.0 eslint: `eslint "." "--ext" ".jsx,.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-webpack-rails-tutorial@1.1.0 eslint script 'eslint "." "--ext" ".jsx,.js"'.
npm ERR! This is most likely a problem with the react-webpack-rails-tutorial package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint "." "--ext" ".jsx,.js"
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-webpack-rails-tutorial
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/justin/a/react-webpack-rails-tutorial/client/npm-debug.log
rake aborted!
Command failed with status (1): [cd client && npm run eslint . -- --ext .js...]
/Users/justin/a/react-webpack-rails-tutorial/lib/tasks/linters.rake:43:in `block (2 levels) in <top (required)>'
/Users/justin/.rvm/gems/ruby-2.2.2@rails42/bin/ruby_executable_hooks:15:in `eval'
/Users/justin/.rvm/gems/ruby-2.2.2@rails42/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => ci => ci:all => lint => lint:lint => lint:js => lint:eslint
(See full trace by running task with --trace)
```

**Comment by justin808** [comment]
either running `rake lint` or `client bin/lint` should give you these errors.

**Comment by mapreal19** [comment]
@justin808 I didn't see those because I had the wrong node version :/

I'll work on it

**Comment by mapreal19** [comment]
@alexfedoseev thanks for the help!

**Comment by alexfedoseev** [comment]
:+1:

**Pull request merged**
